# Generated by Django 2.2 on 2019-04-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubConnectedUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorid', models.IntegerField()),
                ('fullname', models.CharField(max_length=144)),
                ('avatarurl', models.CharField(max_length=244)),
                ('orgs', models.CharField(max_length=90000)),
                ('followers', models.IntegerField()),
                ('repos_dict_with_full_info', models.CharField(max_length=90000)),
                ('client_ID_and_secret', models.CharField(max_length=144)),
            ],
        ),
    ]
