# Generated by Django 2.2 on 2019-04-27 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubConnectedUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authorid', models.IntegerField()),
                ('fullname', models.CharField(max_length=144)),
                ('avatarurl', models.CharField(max_length=244)),
                ('orgs', models.CharField(max_length=90000)),
                ('followers', models.IntegerField()),
                ('repos_dict_with_full_info', models.CharField(max_length=90000)),
                ('client_ID_and_secret', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
