# Generated by Django 2.1.5 on 2019-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubconnectedusers',
            name='moreprofinfo',
            field=models.CharField(default='', max_length=90000),
        ),
    ]
