# Generated by Django 2.2 on 2019-04-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GithubConnectedUsers',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
